# Generated by Django 5.2.9 on 2025-12-05 14:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('pub', 'Pub'), ('cafe', 'Café'), ('park', 'Park'), ('other', 'Other')], default='other', help_text='Type of place.', max_length=32),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, help_text='Short description.'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic location (WGS84 lat/lon).', srid=4326),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Name of the place.', max_length=200),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='places_plac_categor_0dcb38_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(help_text='Place where the event takes place.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='places.place'),
        ),
    ]
