"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import platform

# --- GeoDjango / GDAL config for Windows ---
if os.name == "nt":  # 'nt' means Windows
    # This is where OSGeo4W is installed on your machine
    OSGEO4W_ROOT = r"C:\OSGeo4W"

    if os.path.isdir(OSGEO4W_ROOT):
        os.environ["OSGEO4W_ROOT"] = OSGEO4W_ROOT
        os.environ["GDAL_DATA"] = OSGEO4W_ROOT + r"\share\gdal"
        os.environ["PROJ_LIB"] = OSGEO4W_ROOT + r"\share\proj"
        os.environ["PATH"] = OSGEO4W_ROOT + r"\bin;" + os.environ.get("PATH", "")
    # If the folder doesn't exist we just skip this; Django will complain later if GDAL is missing
# --- end GeoDjango / GDAL config ---

if platform.system() == "Windows":
    os.environ.setdefault("GDAL_LIBRARY_PATH", r"C:\OSGeo4W\bin\gdal311.dll")
    os.environ.setdefault("GEOS_LIBRARY_PATH", r"C:\OSGeo4W\bin\geos_c.dll")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!gg4%w6xk)b*d^lm10otj-t#=m7rla#xolyda!$ke#_9hl)ytk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # GeoDjango
    "django.contrib.gis",

    # Third-party
    "rest_framework",
    "rest_framework_gis",

    # Your app
    "places",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

BASE_DIR = Path(__file__).resolve().parent.parent


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGRES_DB", "lbsdb"),
        "USER": os.getenv("POSTGRES_USER", "lbsuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "lbspassword"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),  # 'localhost' for local dev
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # dev only – open API
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [],  # no auth, no CSRF for now
}

